root: ./

​structure:
    readme: README.md
    summary: SUMMARY.md

redirects:
    tutorials/creating-a-custom-dashboard: tutorials/creating-a-custom-dashboard/README.md
    extending/property-editors/declaring-your-property-editor: tutorials/creating-a-property-editor/README.md
    reference/management/services/create-a-new-user: reference/management/services/managing-users.md
    reference/management/services/auditservice: reference/management/README.md
    reference/management/services/contentservice: reference/management/README.md
    reference/management/services/contenttypeservice: reference/management/README.md
    reference/management/services/contenttypeservice/retrieving-content-type-containers: reference/management/using-services/contenttypeservice.md
    reference/management/services/datatypeservice: reference/management/README.md 
    reference/management/services/domainservice: reference/management/README.md
    reference/management/services/entityservice: reference/management/README.md
    reference/management/services/externalloginservice: reference/management/README.md
    reference/management/services/fileservice: reference/management/README.md
    reference/management/services/localizationservice: reference/management/README.md
    reference/management/services/macroservice: reference/management/README.md
    reference/management/services/membergroupservice: reference/management/README.md
    reference/management/services/memberservice: reference/management/README.md
    reference/management/services/membertypeservice: reference/management/README.md
    reference/management/services/notificationservice: reference/management/README.md
    reference/management/services/packagingservice: reference/management/README.md
    reference/management/services/publicaccessservice: reference/management/README.md
    reference/management/services/redirecturlservice: reference/management/README.md
    reference/management/services/serverregistrationservice: reference/management/README.md
    reference/management/services/tagservice: reference/management/README.md
    reference/management/services/textservice: reference/management/README.md
    reference/management/services/userservice: reference/management/using-services/userservice.md
    reference/management/models: reference/management/README.md
    reference/management/models/content: reference/management/README.md
    reference/management/models/contenttype: reference/management/README.md
    reference/management/models/datatype: reference/management/README.md
    reference/management/models/dictionaryitem: reference/management/README.md
    reference/management/models/language: reference/management/README.md
    reference/management/models/media: reference/management/README.md
    reference/management/models/mediatype: reference/management/README.md
    reference/management/models/relation: reference/management/README.md
    reference/management/models/relationtype: reference/management/README.md
    reference/management/models/serverregistration: reference/management/README.md
    reference/management/models/template: reference/management/README.md
    reference/management/services: reference/management/using-services/README.md
    reference/management/services/consentservice: reference/management/using-services/consentservice.md
    reference/management/services/mediaservice: reference/management/using-services/mediaservice.md
    reference/management/services/relationservice: reference/management/using-services/relationservice.md
    reference/management/services/create-content-programmatically: reference/management/using-services/contentservice.md
    reference/management/services/retrieving-content-types: reference/management/using-services/contenttypeservice.md
    reference/management/services/retrieving-languages: reference/management/using-services/localizationservice.md
    reference/management/services/managing-users: reference/management/using-services/userservice.md
