root: ./

​structure:
    readme: README.md
    summary: SUMMARY.md

redirects:
    fundamentals/setup/install/running-umbraco-on-a-mac: fundamentals/setup/install/running-umbraco-on-linux-macos.md
    reference/security/authenticate-with-active-directory: tutorials/add-azure-active-directory-authentication.md
