root: ./

​structure:  
    readme: README.md
    summary: SUMMARY.md

redirects:
    set-up/manage-hostnames/rewrites-on-cloud: set-up/project-settings/manage-hostnames/rewrites-on-cloud.md
    set-up/manage-security: set-up/project-settings/manage-security.md
    set-up/manage-cdn-caching: set-up/project-settings/manage-cdn-caching.md
    set-up/external-services: set-up/project-settings/external-services.md
    set-up/dedicated-resources: set-up/project-settings/dedicated-resources.md
    upgrades/migrating-from-8-10: upgrades/major-upgrades.md
    upgrades/migrate-from-umbraco-10-to-11: upgrades/major-upgrades.md
